nome=input('digite seu nome completo:')
nome=(nome.lower())
print('silva' in nome)
print(nome.count('silva'))
print(nome.upper())
print(nome.lower())
print(nome.lstrip())
print(len(nome))
print(len(nome.strip()))
nome=(nome.split())
print(len(nome[0]))